export type Course = {
  name: string;
  code: string;
};

export type Subject = {
  id: string;
  label: string;
  icon: string;
  courses: Course[];
};

export const SUBJECTS: Subject[] = [
  {
    id: 'math',
    label: 'Mathematics',
    icon: '∑',
    courses: [
      { name: 'Calculus I', code: 'MATH 1A' },
      { name: 'Calculus II', code: 'MATH 1B' },
      { name: 'Calculus III (Multivariable)', code: 'MATH 53' },
      { name: 'Linear Algebra', code: 'MATH 54' },
      { name: 'Differential Equations', code: 'MATH 55' },
      { name: 'Discrete Mathematics', code: 'MATH 70' },
      { name: 'Statistics', code: 'STAT 20' },
      { name: 'Probability Theory', code: 'STAT 134' },
      { name: 'Real Analysis', code: 'MATH 104' },
      { name: 'Abstract Algebra', code: 'MATH 113' },
      { name: 'Number Theory', code: 'MATH 115' },
      { name: 'Numerical Analysis', code: 'MATH 128A' },
      { name: 'Complex Analysis', code: 'MATH 185' },
      { name: 'Topology', code: 'MATH 142' },
    ],
  },
  {
    id: 'cs',
    label: 'Computer Science',
    icon: '</> ',
    courses: [
      { name: 'Intro to Programming', code: 'CS 10' },
      { name: 'Data Structures', code: 'CS 61B' },
      { name: 'Computer Organization', code: 'CS 61C' },
      { name: 'Algorithms', code: 'CS 170' },
      { name: 'Operating Systems', code: 'CS 162' },
      { name: 'Databases', code: 'CS 186' },
      { name: 'Machine Learning', code: 'CS 189' },
      { name: 'Artificial Intelligence', code: 'CS 188' },
      { name: 'Computer Networks', code: 'CS 168' },
      { name: 'Software Engineering', code: 'CS 169' },
      { name: 'Computer Graphics', code: 'CS 184' },
      { name: 'Cybersecurity', code: 'CS 161' },
      { name: 'Computer Vision', code: 'CS 280' },
      { name: 'Natural Language Processing', code: 'CS 288' },
    ],
  },
  {
    id: 'bio',
    label: 'Biology',
    icon: '🧬',
    courses: [
      { name: 'General Biology I', code: 'BIO 1A' },
      { name: 'General Biology II', code: 'BIO 1B' },
      { name: 'Cell Biology', code: 'MCB 130' },
      { name: 'Genetics', code: 'MCB 140' },
      { name: 'Microbiology', code: 'MCB 150' },
      { name: 'Biochemistry', code: 'MCB 102' },
      { name: 'Neuroscience', code: 'MCB 166' },
      { name: 'Ecology', code: 'IB 160' },
      { name: 'Evolutionary Biology', code: 'IB 164' },
      { name: 'Anatomy & Physiology', code: 'BIO 132' },
      { name: 'Marine Biology', code: 'IB 158' },
      { name: 'Plant Biology', code: 'PMB 111' },
    ],
  },
  {
    id: 'chem',
    label: 'Chemistry',
    icon: '⚗️',
    courses: [
      { name: 'General Chemistry I', code: 'CHEM 1A' },
      { name: 'General Chemistry II', code: 'CHEM 1B' },
      { name: 'Organic Chemistry I', code: 'CHEM 3A' },
      { name: 'Organic Chemistry II', code: 'CHEM 3B' },
      { name: 'Physical Chemistry I', code: 'CHEM 120A' },
      { name: 'Physical Chemistry II', code: 'CHEM 120B' },
      { name: 'Analytical Chemistry', code: 'CHEM 105' },
      { name: 'Inorganic Chemistry', code: 'CHEM 108' },
      { name: 'Biochemistry', code: 'CHEM 135' },
      { name: 'Environmental Chemistry', code: 'CHEM 115' },
    ],
  },
  {
    id: 'physics',
    label: 'Physics',
    icon: '⚛️',
    courses: [
      { name: 'Physics I — Mechanics', code: 'PHYS 7A' },
      { name: 'Physics II — Waves & Heat', code: 'PHYS 7B' },
      { name: 'Physics III — Electromagnetism', code: 'PHYS 7C' },
      { name: 'Modern Physics', code: 'PHYS 137A' },
      { name: 'Quantum Mechanics', code: 'PHYS 137B' },
      { name: 'Classical Mechanics', code: 'PHYS 105' },
      { name: 'Thermodynamics & Stat Mech', code: 'PHYS 112' },
      { name: 'Electrodynamics', code: 'PHYS 110A' },
      { name: 'Astrophysics', code: 'ASTRO 160' },
      { name: 'Optics', code: 'PHYS 111' },
    ],
  },
  {
    id: 'history',
    label: 'History',
    icon: '📜',
    courses: [
      { name: 'World History I', code: 'HIST 1' },
      { name: 'World History II', code: 'HIST 2' },
      { name: 'US History I', code: 'HIST 7A' },
      { name: 'US History II', code: 'HIST 7B' },
      { name: 'Ancient Civilizations', code: 'HIST 115' },
      { name: 'Medieval History', code: 'HIST 100A' },
      { name: 'European History', code: 'HIST 100B' },
      { name: 'Latin American History', code: 'HIST 130A' },
      { name: 'Asian History', code: 'HIST 120' },
      { name: 'African History', code: 'HIST 140' },
      { name: 'History of Science', code: 'HIST 180' },
      { name: 'Modern History', code: 'HIST 100C' },
    ],
  },
  {
    id: 'english',
    label: 'English',
    icon: '📝',
    courses: [
      { name: 'English Composition', code: 'ENGL 1A' },
      { name: 'Critical Thinking & Writing', code: 'ENGL 1B' },
      { name: 'Literature Survey', code: 'ENGL 45A' },
      { name: 'American Literature', code: 'ENGL 45B' },
      { name: 'British Literature', code: 'ENGL 45C' },
      { name: 'World Literature', code: 'ENGL 60' },
      { name: 'Creative Writing', code: 'ENGL 47A' },
      { name: 'Technical Writing', code: 'ENGL 190' },
      { name: 'Shakespeare', code: 'ENGL 117' },
      { name: 'Poetry', code: 'ENGL 140' },
    ],
  },
  {
    id: 'econ',
    label: 'Economics',
    icon: '📈',
    courses: [
      { name: 'Microeconomics', code: 'ECON 1' },
      { name: 'Macroeconomics', code: 'ECON 2' },
      { name: 'Econometrics', code: 'ECON 140' },
      { name: 'Game Theory', code: 'ECON 101A' },
      { name: 'Development Economics', code: 'ECON 181' },
      { name: 'International Trade', code: 'ECON 182' },
      { name: 'Labor Economics', code: 'ECON 150A' },
      { name: 'Public Finance', code: 'ECON 131' },
      { name: 'Behavioral Economics', code: 'ECON 119' },
      { name: 'Financial Economics', code: 'ECON 136' },
    ],
  },
  {
    id: 'psych',
    label: 'Psychology',
    icon: '🧠',
    courses: [
      { name: 'Introduction to Psychology', code: 'PSYCH 1' },
      { name: 'Social Psychology', code: 'PSYCH 160' },
      { name: 'Developmental Psychology', code: 'PSYCH 130' },
      { name: 'Cognitive Psychology', code: 'PSYCH 120' },
      { name: 'Abnormal Psychology', code: 'PSYCH 150A' },
      { name: 'Research Methods', code: 'PSYCH 101' },
      { name: 'Behavioral Neuroscience', code: 'PSYCH 110' },
      { name: 'Personality', code: 'PSYCH 140' },
      { name: 'Health Psychology', code: 'PSYCH 152' },
      { name: 'Industrial-Org Psychology', code: 'PSYCH 102' },
    ],
  },
  {
    id: 'engineering',
    label: 'Engineering',
    icon: '⚙️',
    courses: [
      { name: 'Statics', code: 'ME 85' },
      { name: 'Dynamics', code: 'ME 170' },
      { name: 'Thermodynamics', code: 'ME 40' },
      { name: 'Circuit Analysis', code: 'EECS 16A' },
      { name: 'Signals & Systems', code: 'EECS 120' },
      { name: 'Fluid Mechanics', code: 'ME 106' },
      { name: 'Materials Science', code: 'MSE 45' },
      { name: 'Structural Analysis', code: 'CE 120' },
      { name: 'Control Systems', code: 'ME 132' },
      { name: 'Heat Transfer', code: 'ME 109' },
      { name: 'Solid Mechanics', code: 'CE 130' },
    ],
  },
  {
    id: 'poli',
    label: 'Political Science',
    icon: '🏛️',
    courses: [
      { name: 'Introduction to Political Science', code: 'POLSCI 1' },
      { name: 'American Politics', code: 'POLSCI 2' },
      { name: 'International Relations', code: 'POLSCI 124A' },
      { name: 'Comparative Politics', code: 'POLSCI 3' },
      { name: 'Political Theory', code: 'POLSCI 104A' },
      { name: 'Public Policy', code: 'POLSCI 137' },
      { name: 'Constitutional Law', code: 'POLSCI 135A' },
      { name: 'Political Economy', code: 'POLSCI 120A' },
    ],
  },
  {
    id: 'sociology',
    label: 'Sociology',
    icon: '👥',
    courses: [
      { name: 'Introduction to Sociology', code: 'SOC 1' },
      { name: 'Social Stratification', code: 'SOC 110' },
      { name: 'Race & Ethnicity', code: 'SOC 130' },
      { name: 'Gender & Society', code: 'SOC 104' },
      { name: 'Sociology of Education', code: 'SOC 155' },
      { name: 'Urban Sociology', code: 'SOC 120' },
      { name: 'Research Methods', code: 'SOC 101' },
      { name: 'Social Theory', code: 'SOC 102' },
    ],
  },
];
